#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

echo "Cleaning OpenFOAM case..."

# Remove time directories (except 0)
rm -rf [1-9]* 0.[0-9]* 0.0[1-9]*

# Remove processor directories
rm -rf processor*

# Remove log files
rm -f log.*

# Remove postProcessing
rm -rf postProcessing

# Remove dynamicCode
rm -rf dynamicCode

echo "Case cleaned!"
